[package]
name = "block_kutin"
version = "0.1.0"


[dependencies]
itertools = "0.10.5"
clap = { version = "4.2.4", features = ["derive", "cargo"] }
pyo3 = { version = "0.18.2", features = ["extension-module"] }