[package]
name = "kutin_enumeration_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
clap = { version = "4.2.4", features = ["derive", "cargo"] }